# Site
repository: nikhilkumar5294/nikhilkumar5294.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nikhil Kumar
title: Backend Developer
email: hello@nikhilkumar.dev
# website: www.nikhilkumar.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  nikhilkumar5294
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: nikhilkumar5294
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Nikhil Kumar, I'm a backend developer with over 5 years experience currently specialising in Golang development.
  I am currently working for Maplelabs Solution Pvt Ltd as a Senior Software Engineer on their comercial observability platform, Snappyflow.
  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work with something new. 
  The things that I currently have the most experience working with are:
  <mark>Golang</mark>,
  <mark>Kubernetes</mark>,
  <mark>AWS</mark>,
  <mark>Elasticsearch</mark>,
  <mark>PostgreSQL</mark>.


content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Maplelabs Solution Pvt Ltd
        link: maplelabs.com
        # link_text: boringcompany.com
        sub_title: Senior Sofrtware Engineer
        caption: January 2020 - Present
        # quote: >
        #   Building Snappyflow - Observability Simplified
        description: | # this will include new lines to allow paragraphs
            Working on Snappyflow development

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bundelkhand Institute of Engineering and Technology
        caption: 2012 - 2016
        sub_title: B.TECH (Information Technology)
        # quote: >
        #   Established in 1986, BIET is the fifth government engineering college in the U.P.
        description: | # this will include new lines to allow paragraphs
          During my time at BIET Jhansi I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time at BIET  and learnt a lot about a healthy work life balance.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Taching Anime
      - Gaming
      - Travelling

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
